# Generated by Django 2.0.4 on 2018-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(default='BANNERS', max_length=30, verbose_name='广告材料格式')),
                ('geo', models.CharField(default='CHN', max_length=100, verbose_name='地理位置')),
                ('category', models.CharField(default='2', max_length=10, verbose_name='类别')),
                ('network_selection_type', models.CharField(default='0', max_length=50, verbose_name='网络选择类型')),
                ('web_cpc', models.CharField(default='0.01', max_length=10, verbose_name='web cpc')),
                ('mobile_cpc', models.CharField(default='0.01', max_length=10, verbose_name='mobile cpc')),
                ('web_cpm', models.CharField(default='0.01', max_length=10, verbose_name='web cpm')),
                ('mobile_cpm', models.CharField(default='0.01', max_length=10, verbose_name='mobile cpm')),
            ],
            options={
                'verbose_name': '广告最低价格表',
                'verbose_name_plural': '广告最低价格表',
            },
        ),
    ]
