# Generated by Django 2.0.4 on 2018-04-16 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostDailyTrendReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(db_index=True, default='0.00', null=True, verbose_name='消费')),
                ('exchangeRate', models.FloatField(db_index=True, default='0.00', max_length=50, null=True, verbose_name='汇率')),
                ('deliveryRate', models.FloatField(db_index=True, default='0.00', max_length=50, null=True, verbose_name='投放率')),
                ('date', models.DateField(default=datetime.datetime.now, null=True, verbose_name='消费日期')),
            ],
            options={
                'verbose_name': '消费日趋势报表',
                'verbose_name_plural': '消费日趋势报表',
            },
        ),
        migrations.CreateModel(
            name='CostHourTrendReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(db_index=True, default='0.00', null=True, verbose_name='消费')),
                ('exchangeRate', models.FloatField(db_index=True, default='0.00', max_length=50, null=True, verbose_name='汇率')),
                ('deliveryRate', models.FloatField(db_index=True, default='0.00', max_length=50, null=True, verbose_name='投放率')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='消费日期')),
            ],
            options={
                'verbose_name': '消费时趋势报表',
                'verbose_name_plural': '消费时趋势报表',
            },
        ),
    ]
