# Generated by Django 2.0.4 on 2018-04-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costtrendreport', '0001_initial'),
        ('designad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costhourtrendreport',
            name='adCampaigns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designad.DesignAdList', verbose_name='所属广告活动'),
        ),
    ]
