# Generated by Django 2.0.4 on 2018-05-04 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costtrendreport', '0003_auto_20180416_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costhourtrendreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='消费日期（纽约时间）'),
        ),
    ]
