# Generated by Django 2.0.4 on 2018-05-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costtrendreport', '0004_auto_20180504_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costdailytrendreport',
            name='exchangeRate',
        ),
        migrations.RemoveField(
            model_name='costhourtrendreport',
            name='exchangeRate',
        ),
    ]
