# Generated by Django 2.0.4 on 2018-04-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useracount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useracount',
            options={'verbose_name': '用户消费余额信息', 'verbose_name_plural': '用户消费余额信息'},
        ),
        migrations.AddField(
            model_name='useracount',
            name='deliveryRate',
            field=models.FloatField(db_index=True, default='0.00', max_length=50, null=True, verbose_name='投放率'),
        ),
        migrations.AddField(
            model_name='useracount',
            name='exchangeRate',
            field=models.FloatField(db_index=True, default='0.00', max_length=50, null=True, verbose_name='汇率'),
        ),
    ]
