# Generated by Django 2.0.4 on 2018-05-09 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180418_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='用户充值金额')),
                ('exo_recharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='EXO充值金额')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户充值记录',
                'verbose_name_plural': '用户充值记录',
            },
        ),
    ]
