# Generated by Django 2.0.4 on 2018-05-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180509_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adpricerate',
            options={'verbose_name': '设置用户投放率', 'verbose_name_plural': '设置用户投放率'},
        ),
    ]
