# Generated by Django 2.0.4 on 2018-05-17 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180517_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpricerate',
            name='deliveryRate',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='输入的投放率必须在0.1到0.9之间', max_digits=10, validators=[django.core.validators.MaxValueValidator(0.9), django.core.validators.MinValueValidator(0.1)], verbose_name='投放率'),
        ),
    ]
