# Generated by Django 2.0.4 on 2018-05-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180517_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracount',
            name='deliveryRate',
        ),
    ]
