# Generated by Django 2.0.4 on 2018-05-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_useracount_deliveryrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerecord',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='充值时EXO的余额'),
        ),
    ]
