# Generated by Django 2.0.4 on 2018-05-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180520_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracount',
            name='recharge_balance',
        ),
    ]
