# Generated by Django 2.0.4 on 2018-05-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_useracount_recharge_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerecord',
            name='recharge_deliveryRate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='本次充值时的投放率'),
        ),
    ]
