# Generated by Django 2.0.4 on 2018-05-04 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costreport', '0003_auto_20180416_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costdailyreport',
            name='avgCpc',
            field=models.FloatField(db_index=True, default='0.00', null=True, verbose_name='Avg_CPC）'),
        ),
        migrations.AlterField(
            model_name='costhourreport',
            name='avgCpc',
            field=models.FloatField(db_index=True, default='0.00', null=True, verbose_name='Avg_CPC'),
        ),
        migrations.AlterField(
            model_name='costhourreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='消费时间（纽约时间）'),
        ),
    ]
