# Generated by Django 2.0.4 on 2018-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costreport', '0004_auto_20180504_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costdailyreport',
            name='avgCpc',
            field=models.FloatField(db_index=True, default='0.00', null=True, verbose_name='Avg_CPC'),
        ),
    ]
