# Generated by Django 2.0.4 on 2018-05-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costreport', '0005_auto_20180509_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costdailyreport',
            name='exchangeRate',
        ),
        migrations.RemoveField(
            model_name='costhourreport',
            name='exchangeRate',
        ),
    ]
