# Generated by Django 2.0.4 on 2018-05-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costreport', '0006_auto_20180509_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costdailyreport',
            name='adCampaigns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='designad.DesignAdList', verbose_name='所属广告活动'),
        ),
        migrations.AlterField(
            model_name='costhourreport',
            name='adCampaigns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='designad.DesignAdList', verbose_name='所属广告活动'),
        ),
    ]
