# Generated by Django 2.0.4 on 2018-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costreport', '0007_auto_20180513_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costdailyreport',
            name='ctr',
            field=models.FloatField(default='0.00', null=True, verbose_name='点击率'),
        ),
        migrations.AlterField(
            model_name='costhourreport',
            name='ctr',
            field=models.FloatField(default='0.00', null=True, verbose_name='点击率'),
        ),
    ]
