# Generated by Django 2.0.4 on 2018-04-16 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_library_file', models.IntegerField(default='1', verbose_name='广告创意ID')),
                ('varId', models.IntegerField(blank=True, default='1', verbose_name='广告内容ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='广告内容添加时间')),
            ],
            options={
                'verbose_name': '广告创意',
                'verbose_name_plural': '广告创意',
            },
        ),
        migrations.CreateModel(
            name='AdGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalId', models.CharField(default='0', max_length=250, null=True, verbose_name='goal的ID')),
                ('idUser', models.CharField(default='0', max_length=250, null=True, verbose_name='用户ID')),
                ('name', models.CharField(default='0', max_length=250, null=True, verbose_name='goal名称')),
                ('seq', models.CharField(default='0', max_length=250, null=True, verbose_name='goal的序列id')),
                ('order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='顺序')),
                ('coa', models.CharField(blank=True, default='0', max_length=250, null=True, verbose_name='成本(可选)')),
                ('goalScript', models.TextField(default='0', max_length=250, null=True, verbose_name='追踪代码')),
            ],
            options={
                'verbose_name': '目标追踪代码',
                'verbose_name_plural': '目标追踪代码',
            },
        ),
        migrations.CreateModel(
            name='AdUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='http://', max_length=250, verbose_name='推广URL')),
                ('varId', models.IntegerField(blank=True, default='1', verbose_name='广告内容ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='广告内容添加时间')),
            ],
            options={
                'verbose_name': '推广URL',
                'verbose_name_plural': '推广URL',
            },
        ),
        migrations.CreateModel(
            name='AdVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, null=True, verbose_name='广告内容名称')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='广告内容简介')),
                ('url', models.CharField(default='http://', help_text='请输入与上面推广URL相同的URL', max_length=250, verbose_name='推广URL')),
                ('status', models.IntegerField(blank=True, default='3', verbose_name='状态')),
                ('id_library_file', models.IntegerField(default='1', verbose_name='广告创意ID')),
                ('varId', models.IntegerField(blank=True, default='1', verbose_name='广告内容ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='广告内容添加时间')),
            ],
            options={
                'verbose_name': '广告内容',
                'verbose_name_plural': '广告内容',
            },
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='投放站点', max_length=128, verbose_name='投放站点')),
            ],
            options={
                'verbose_name': '投放站点',
                'verbose_name_plural': '投放站点',
            },
        ),
        migrations.CreateModel(
            name='AdvertiserAdType',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, verbose_name='广告类型id')),
                ('name', models.CharField(default='', max_length=150, verbose_name='广告类型名称')),
                ('media_storage_templates', models.CharField(default='', max_length=250, verbose_name='广告类型')),
            ],
            options={
                'verbose_name': '广告类型',
                'verbose_name_plural': '广告类型',
            },
        ),
        migrations.CreateModel(
            name='BlocksAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='屏蔽站点', max_length=128, verbose_name='屏蔽站点')),
            ],
            options={
                'verbose_name': '屏蔽站点',
                'verbose_name_plural': '屏蔽站点',
            },
        ),
        migrations.CreateModel(
            name='Browsers',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, verbose_name='浏览器id')),
                ('name', models.CharField(default='Internet Explorer', max_length=128, verbose_name='浏览器名称')),
            ],
            options={
                'verbose_name': '浏览器',
                'verbose_name_plural': '浏览器',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, verbose_name='类别id')),
                ('name', models.CharField(default='屏蔽站点', max_length=128, verbose_name='屏蔽站点')),
                ('parent', models.IntegerField(default=0, verbose_name='父级id')),
            ],
            options={
                'verbose_name': '广告类别',
                'verbose_name_plural': '广告类别',
                'ordering': ['parent'],
            },
        ),
        migrations.CreateModel(
            name='DesignAdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adName', models.CharField(default='', help_text='格式推荐：公司-产品', max_length=250, verbose_name='广告活动名称')),
                ('adStyle', models.CharField(choices=[('Banner - 300x250', '横幅 - 300x250'), ('Banner - 468x60', '横幅 - 468x60'), ('Banner - 728x90', '横幅 - 728x90'), ('Banner - 250x250', '横幅 - 250x250'), ('Banner - 120x600', '横幅 - 120x600'), ('Banner - 160x600', '横幅 - 160x600'), ('Banner - 315x300', '横幅 - 315x300'), ('Mobile - 300x50', '移动 - 300x50'), ('Mobile - 300x100', '移动 - 300x100')], default='Banner - 300x250', max_length=30, verbose_name='广告样式')),
                ('keywords', models.TextField(default='', help_text='提示：每个关键词请换行分开，请不要输入中文', verbose_name='关键词')),
                ('sites', models.TextField(blank=True, default='', help_text='提示：每个站点请换行分开，在站点前加-号代表屏蔽此站点', verbose_name='站点目标定位')),
                ('priceModel', models.CharField(choices=[('1', 'CPC'), ('2', 'CPM'), ('5', 'CPV')], default='1', help_text='此价格模式在创建广告活动之后将不能再更改，请慎选', max_length=20, verbose_name='价格模式')),
                ('price', models.FloatField(default='1', verbose_name='价格')),
                ('maxDailyBudget', models.BigIntegerField(choices=[(-1, '无限'), (2000, '280'), (5000, '700'), (10000, '1400'), (20000, '2800'), (50000, '7000'), (75000, '10500'), (100000, '14000'), (200000, '28000'), (500000, '70000'), (1000000, '140000'), (1500000, '210000'), (2000000, '280000')], default=-1, verbose_name='日均预算上限')),
                ('addAllSite', models.BooleanField(default=True, help_text='提示：默认投放全部站点', verbose_name='投放全部站点')),
                ('adAllTime', models.BooleanField(default=False, help_text='提示：选择了此处，则以下时间不用再选择，每天时间段默认为0:00-0:00，此时间段为一整天', verbose_name='选择全部时间段')),
                ('campaign_id', models.IntegerField(default=1, null=True, verbose_name='广告活动ID')),
                ('status', models.IntegerField(default=3, null=True, verbose_name='状态')),
                ('variation_id', models.CharField(default='', max_length=300, null=True, verbose_name='广告创意ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('checked', models.IntegerField(default='0', null=True, verbose_name='是否过审')),
                ('isPost', models.IntegerField(default='0', null=True, verbose_name='是否上传')),
            ],
            options={
                'verbose_name': '新建广告活动',
                'verbose_name_plural': '新建广告活动',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, verbose_name='设备id')),
                ('name', models.CharField(default='Desktop', max_length=128, verbose_name='设备名称')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friTime', models.CharField(default='8:00', max_length=128, verbose_name='星期五时间')),
            ],
            options={
                'verbose_name': '星期五时间',
                'verbose_name_plural': '星期五时间',
            },
        ),
        migrations.CreateModel(
            name='GeographicLocation',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, verbose_name='地理位置id')),
                ('short_name', models.CharField(default='China', max_length=128, verbose_name='地理位置简称')),
                ('long_name', models.CharField(default='China', max_length=250, verbose_name='地理位置简称')),
                ('chn_name', models.CharField(max_length=250, verbose_name='地理位置中文名称')),
                ('iso2', models.CharField(default='ch', max_length=50, verbose_name='地理位置名称ios2版本')),
                ('iso3', models.CharField(default='ch', max_length=50, verbose_name='地理位置名称ios3版本')),
            ],
            options={
                'verbose_name': '地理位置',
                'verbose_name_plural': '地理位置',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, verbose_name='语言id')),
                ('name', models.CharField(default='China', max_length=100, verbose_name='语言名称')),
                ('chn_name', models.CharField(max_length=100, verbose_name='语言中文名称')),
                ('iso2', models.CharField(default='ch', max_length=50, verbose_name='语言名称ios2版本')),
                ('iso2_two', models.CharField(default='ch', max_length=50, verbose_name='语言名称ios2第二版本')),
            ],
            options={
                'verbose_name': '语言',
                'verbose_name_plural': '语言',
            },
        ),
        migrations.CreateModel(
            name='MobileCarriers',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, verbose_name='移动运营商id')),
                ('name', models.CharField(default='Internet Explorer', max_length=128, verbose_name='移动运营商名称')),
                ('country_id', models.IntegerField(default=1, verbose_name='国家id')),
                ('enabled', models.IntegerField(default=1, verbose_name='移动运营商可用状态')),
            ],
            options={
                'verbose_name': '移动运营商',
                'verbose_name_plural': '移动运营商',
            },
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monTime', models.CharField(default='8:00', max_length=128, verbose_name='星期一时间')),
            ],
            options={
                'verbose_name': '星期一时间',
                'verbose_name_plural': '星期一时间',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystems',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, verbose_name='操作系统id')),
                ('name', models.CharField(default='Windows 8.1', max_length=128, verbose_name='操作系统名称')),
                ('type', models.IntegerField(default=0, verbose_name='操作系统类型')),
            ],
            options={
                'verbose_name': '操作系统',
                'verbose_name_plural': '操作系统',
            },
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satTime', models.CharField(default='8:00', max_length=128, verbose_name='星期六时间')),
            ],
            options={
                'verbose_name': '星期六时间',
                'verbose_name_plural': '星期六时间',
            },
        ),
        migrations.CreateModel(
            name='SitesData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_hostname', models.CharField(db_index=True, default='semyes.cn', max_length=250, verbose_name='站点')),
                ('cost', models.FloatField(db_index=True, default='0.00', null=True, verbose_name='消费')),
                ('impressions', models.IntegerField(default='0', null=True, verbose_name='展现次数')),
                ('clicks', models.IntegerField(default='0', null=True, verbose_name='点击次数')),
                ('avgCpc', models.FloatField(db_index=True, default='0.00', null=True, verbose_name='平均点击价格（AvgCPC）')),
                ('avgCpm', models.FloatField(db_index=True, default='0.00', null=True, verbose_name='平均展示价格（AvgCPM）')),
                ('ctr', models.CharField(default='0.00', max_length=50, null=True, verbose_name='点击率')),
                ('cpc', models.FloatField(default='0.00', null=True, verbose_name='CPC')),
                ('cpv', models.FloatField(default='0.00', null=True, verbose_name='CPV')),
                ('cpm', models.FloatField(default='0.00', null=True, verbose_name='CPM')),
                ('G1', models.FloatField(default='0', null=True, verbose_name='G1')),
                ('ecpa1', models.FloatField(db_index=True, default='0', null=True, verbose_name='ecpa1')),
                ('G2', models.FloatField(default='0', null=True, verbose_name='G2')),
                ('ecpa2', models.FloatField(db_index=True, default='0', null=True, verbose_name='ecpa2')),
                ('G3', models.FloatField(default='0', null=True, verbose_name='G3')),
                ('ecpa3', models.FloatField(db_index=True, default='0', null=True, verbose_name='ecpa3')),
                ('G4', models.FloatField(default='0', null=True, verbose_name='G4')),
                ('ecpa4', models.FloatField(db_index=True, default='0', null=True, verbose_name='ecpa4')),
                ('exchangeRate', models.FloatField(db_index=True, default='0.00', max_length=50, null=True, verbose_name='差价')),
                ('deliveryRate', models.FloatField(db_index=True, default='0.00', max_length=50, null=True, verbose_name='初始消费')),
                ('date', models.DateField(default=datetime.datetime.now, max_length=50, null=True, verbose_name='消费时间')),
            ],
            options={
                'verbose_name': '站点统计数据',
                'verbose_name_plural': '站点统计数据',
            },
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunTime', models.CharField(default='8:00', max_length=128, verbose_name='星期日时间')),
            ],
            options={
                'verbose_name': '星期日时间',
                'verbose_name_plural': '星期日时间',
            },
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thurTime', models.CharField(default='8:00', max_length=128, verbose_name='星期四时间')),
            ],
            options={
                'verbose_name': '星期四时间',
                'verbose_name_plural': '星期四时间',
            },
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tueTime', models.CharField(default='8:00', max_length=128, verbose_name='星期二时间')),
            ],
            options={
                'verbose_name': '星期二时间',
                'verbose_name_plural': '星期二时间',
            },
        ),
        migrations.CreateModel(
            name='UserAdFileLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adMaterial', models.FileField(default='', help_text='提示：上传的广告创意的尺寸大小有：300x250、468x60、728x90、250x250、120x600、160x600、315x300、300x50、300x100（格式：宽x高），否则影响推广效果，可上传jpg、png、gif格式,gif图的动画速度不能太快，否则此广告会审核不过', upload_to='designad/%Y/%m', verbose_name='广告素材')),
                ('file_name', models.CharField(default='', max_length=250, verbose_name='文件名称')),
                ('file_id', models.BigIntegerField(default='1', verbose_name='文件id')),
                ('type', models.CharField(default='', max_length=50, verbose_name='创意类型')),
                ('width', models.CharField(default='', max_length=50, verbose_name='创意的宽')),
                ('height', models.CharField(default='', max_length=50, verbose_name='创意的高')),
                ('file_extension', models.CharField(default='', max_length=50, verbose_name='创意后缀名')),
                ('file_size', models.CharField(default='', max_length=50, verbose_name='创意大小')),
                ('url', models.CharField(default='', max_length=250, verbose_name='创意url')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创意添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='创意更新时间')),
            ],
            options={
                'verbose_name': '广告创意',
                'verbose_name_plural': '广告创意',
            },
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedTime', models.CharField(default='8:00', max_length=128, verbose_name='星期三时间')),
            ],
            options={
                'verbose_name': '星期三时间',
                'verbose_name_plural': '星期三时间',
            },
        ),
    ]
