# Generated by Django 2.0.4 on 2018-04-16 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradfilelibrary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='sitesdata',
            name='adCampaigns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designad.DesignAdList', verbose_name='所属广告活动'),
        ),
        migrations.AddField(
            model_name='sitesdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='adUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='browsersList',
            field=models.ManyToManyField(blank=True, to='designad.Browsers', verbose_name='浏览器'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='categoriesList',
            field=models.ManyToManyField(blank=True, to='designad.Categories', verbose_name='广告类别'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='devicesList',
            field=models.ManyToManyField(blank=True, to='designad.Devices', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='fridayList',
            field=models.ManyToManyField(blank=True, to='designad.Friday', verbose_name='星期五时间'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='geographicLocationList',
            field=models.ManyToManyField(blank=True, to='designad.GeographicLocation', verbose_name='地理位置'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='languagesList',
            field=models.ManyToManyField(blank=True, to='designad.Languages', verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='mobileCarriersList',
            field=models.ManyToManyField(blank=True, to='designad.MobileCarriers', verbose_name='移动运营商'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='mondayList',
            field=models.ManyToManyField(blank=True, to='designad.Monday', verbose_name='星期一时间'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='operatingSystemList',
            field=models.ManyToManyField(blank=True, to='designad.OperatingSystems', verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='saturdayList',
            field=models.ManyToManyField(blank=True, to='designad.Saturday', verbose_name='星期六时间'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='sundayList',
            field=models.ManyToManyField(blank=True, to='designad.Sunday', verbose_name='星期日时间'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='thursdayList',
            field=models.ManyToManyField(blank=True, to='designad.Thursday', verbose_name='星期四时间'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='tuesdayList',
            field=models.ManyToManyField(blank=True, to='designad.Tuesday', verbose_name='星期二时间'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='wednesdayList',
            field=models.ManyToManyField(blank=True, to='designad.Wednesday', verbose_name='星期三时间'),
        ),
        migrations.AddField(
            model_name='advariation',
            name='adCampaigns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designad.DesignAdList', verbose_name='所属广告活动'),
        ),
        migrations.AddField(
            model_name='advariation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='adurl',
            name='adCampaigns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designad.DesignAdList', verbose_name='所属广告活动'),
        ),
        migrations.AddField(
            model_name='adurl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='adgoals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='adCampaigns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designad.DesignAdList', verbose_name='所属广告活动'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.CreateModel(
            name='DesignAdSite',
            fields=[
            ],
            options={
                'verbose_name': '站点目标定位',
                'verbose_name_plural': '站点目标定位',
                'proxy': True,
                'indexes': [],
            },
            bases=('designad.designadlist',),
        ),
    ]
