# Generated by Django 2.0.4 on 2018-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0002_auto_20180416_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designadlist',
            name='price',
            field=models.FloatField(default='1', help_text='CPC模式的价格不能超过11.60', verbose_name='价格'),
        ),
    ]
