# Generated by Django 2.0.4 on 2018-04-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0003_auto_20180416_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographiclocation',
            name='chn_name',
        ),
        migrations.RemoveField(
            model_name='geographiclocation',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='geographiclocation',
            name='short_name',
        ),
    ]
