# Generated by Django 2.0.4 on 2018-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0005_geographiclocation_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographiclocation',
            name='short_name',
            field=models.CharField(default='China', max_length=128, verbose_name='地理位置简称'),
        ),
    ]
