# Generated by Django 2.0.4 on 2018-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0006_geographiclocation_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographiclocation',
            name='chn_name',
            field=models.CharField(default=2, max_length=250, verbose_name='地理位置中文名称'),
            preserve_default=False,
        ),
    ]
