# Generated by Django 2.0.4 on 2018-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0007_geographiclocation_chn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesdata',
            name='G1',
            field=models.IntegerField(default=0, null=True, verbose_name='G1'),
        ),
        migrations.AlterField(
            model_name='sitesdata',
            name='G2',
            field=models.IntegerField(default=0, null=True, verbose_name='G2'),
        ),
        migrations.AlterField(
            model_name='sitesdata',
            name='G3',
            field=models.IntegerField(default=0, null=True, verbose_name='G3'),
        ),
        migrations.AlterField(
            model_name='sitesdata',
            name='G4',
            field=models.IntegerField(default=0, null=True, verbose_name='G4'),
        ),
        migrations.AlterField(
            model_name='sitesdata',
            name='ecpa1',
            field=models.FloatField(db_index=True, default=0, null=True, verbose_name='ecpa1'),
        ),
        migrations.AlterField(
            model_name='sitesdata',
            name='ecpa2',
            field=models.FloatField(db_index=True, default=0, null=True, verbose_name='ecpa2'),
        ),
        migrations.AlterField(
            model_name='sitesdata',
            name='ecpa3',
            field=models.FloatField(db_index=True, default=0, null=True, verbose_name='ecpa3'),
        ),
        migrations.AlterField(
            model_name='sitesdata',
            name='ecpa4',
            field=models.FloatField(db_index=True, default=0, null=True, verbose_name='ecpa4'),
        ),
    ]
