# Generated by Django 2.0.4 on 2018-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0009_auto_20180504_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='advariation',
            name='vari_url',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='创意URL'),
        ),
    ]
