# Generated by Django 2.0.4 on 2018-05-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0010_advariation_vari_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesdata',
            name='exchangeRate',
        ),
    ]
