# Generated by Django 2.0.4 on 2018-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0011_remove_sitesdata_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='designadlist',
            name='enabled',
            field=models.IntegerField(choices=[(1, '小时'), (0, '分钟')], default=True, verbose_name='显示频率按分钟或小时'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='impressions',
            field=models.IntegerField(default=0, help_text='提示:选择了“显示频率“中的“开启”后才能生效', verbose_name='展现量'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='impressionsEnabled',
            field=models.BooleanField(choices=[(True, '开启'), (False, '关闭')], default=False, help_text='只有当价格模式是CPM时才需要开启', max_length=30, verbose_name='显示频率'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='minutes',
            field=models.IntegerField(default=0, help_text='提示:选择了“显示频率“中的“开启”后才能生效', verbose_name='分钟/小时'),
        ),
    ]
