# Generated by Django 2.0.4 on 2018-05-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0012_auto_20180509_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designadlist',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='designadlist',
            name='variation_id',
        ),
        migrations.AddField(
            model_name='designadlist',
            name='is_hour_or_minutes',
            field=models.IntegerField(blank=True, choices=[(1, '小时'), (0, '分钟')], default=1, help_text='提示：只有当价格模式是CPM时才需要选择分钟或小时', verbose_name='显示频率按分钟或小时'),
        ),
        migrations.AlterField(
            model_name='designadlist',
            name='impressions',
            field=models.IntegerField(blank=True, default=0, help_text='提示：只有当价格模式是CPM时并选择了“显示频率”中的“开启”后才能生效', verbose_name='展现量'),
        ),
        migrations.AlterField(
            model_name='designadlist',
            name='impressionsEnabled',
            field=models.BooleanField(choices=[(True, '开启'), (False, '关闭')], default=False, help_text='提示：只有当价格模式是CPM时才需要开启', max_length=30, verbose_name='显示频率'),
        ),
        migrations.AlterField(
            model_name='designadlist',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, help_text='提示：只有当价格模式是CPM时并选择了“显示频率”中的“开启”后才能生效', verbose_name='分钟/小时'),
        ),
    ]
