# Generated by Django 2.0.4 on 2018-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0013_auto_20180509_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designadlist',
            name='is_hour_or_minutes',
            field=models.IntegerField(blank=True, choices=[(1, '小时'), (2, '分钟')], default=1, help_text='提示：只有当价格模式是CPM时才需要选择分钟或小时', verbose_name='显示频率按分钟或小时'),
        ),
    ]
