# Generated by Django 2.0.4 on 2018-05-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0014_auto_20180509_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designadlist',
            name='is_hour_or_minutes',
        ),
        migrations.AlterField(
            model_name='designadlist',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, help_text='提示：只有当价格模式是CPM时并选择了“显示频率”中的“开启”后才能生效', verbose_name='分钟'),
        ),
    ]
