# Generated by Django 2.0.4 on 2018-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0015_auto_20180509_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designadlist',
            name='impressions',
            field=models.IntegerField(blank=True, default=0, help_text='提示：此项为设置重复访问者在一定时间内显示的次数，只有当价格模式是CPM时并选择了“显示频率”中的“开启”后才能生效', verbose_name='展现量'),
        ),
        migrations.AlterField(
            model_name='designadlist',
            name='impressionsEnabled',
            field=models.BooleanField(choices=[(True, '开启'), (False, '关闭')], default=False, help_text='提示：只有当价格模式是CPM时才需要开启，用以限制一个重复的访问者在一定时间内看到您的广告的次数', max_length=30, verbose_name='显示频率'),
        ),
        migrations.AlterField(
            model_name='designadlist',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, help_text='提示：此项为设置重复访问者显示频率的时间（分钟），只有当价格模式是CPM时并选择了“显示频率”中的“开启”后才能生效', verbose_name='分钟'),
        ),
    ]
