# Generated by Django 2.0.4 on 2018-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0016_auto_20180509_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='designadlist',
            name='adAllBrowsers',
            field=models.BooleanField(default=False, help_text='提示：选择了此处，则以下操作系统不用再选择', verbose_name='选择全部操作系统'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='adAllDevices',
            field=models.BooleanField(default=False, help_text='提示：选择了此处，则以下设备不用再选择', verbose_name='选择全部设备'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='adAllLanguages',
            field=models.BooleanField(default=False, help_text='提示：选择了此处，则以下语言不用再选择', verbose_name='选择全部语言'),
        ),
        migrations.AddField(
            model_name='designadlist',
            name='adAllMobileCarriers',
            field=models.BooleanField(default=False, help_text='提示：选择了此处，则以下移动运营商不用再选择', verbose_name='选择全部移动运营商'),
        ),
        migrations.AlterField(
            model_name='designadlist',
            name='maxDailyBudget',
            field=models.BigIntegerField(choices=[(-1, '无限'), (2000, '40'), (5000, '100'), (10000, '200'), (20000, '400'), (50000, '1000'), (75000, '1500'), (100000, '2000'), (200000, '4000'), (500000, '10000'), (1000000, '20000'), (1500000, '30000'), (2000000, '40000')], default=-1, verbose_name='日均预算上限'),
        ),
        migrations.AlterField(
            model_name='designadlist',
            name='priceModel',
            field=models.CharField(choices=[('1', 'CPC'), ('2', 'CPM'), ('4', 'Smart CPM'), ('5', 'CPV')], default='1', help_text='此价格模式在创建广告活动之后将不能再更改，请慎选', max_length=20, verbose_name='价格模式'),
        ),
    ]
