# Generated by Django 2.0.4 on 2018-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0021_auto_20180513_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designadlist',
            name='adAllDevices',
            field=models.BooleanField(default=True, help_text='提示：选择了此处，则以下设备不用再选择，默认为全选（推荐）', verbose_name='选择全部设备'),
        ),
    ]
