# Generated by Django 2.0.4 on 2018-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designad', '0027_auto_20180517_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesdata',
            name='ctr',
            field=models.FloatField(default='0.00', null=True, verbose_name='点击率'),
        ),
    ]
